title: Jaein Land
author: Jaein Kim
description: NLP and others
url: "https://jaeinkr.github.io"
auto: true
theme: jekyll-theme-minimal
plugins:
- jekyll-seo-tag

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
